name = "rvy/jest_rodeo"
version = "0.0.1"
includes = [
  "pesde.toml",
  "README.md",
  "LICENSE",
  "src/**/*.luau",
  ".luaurc",
]

[engines]
lune = "^0.10.4"
pesde = "^0.7.1"

[target]
environment = "lune"
bin = "src/init.luau"

[dependencies]
pathfs = { name = "jiwonz/pathfs", version = "^0.6.0", target = "lune" }
argparse = { name = "caveful_games/argparse", version = "^0.1.2", target = "lune" }
chalk = { name = "kimpure/chalk_luau", version = "^0.1.8", target = "lune" }
spin = { name = "rvy/spin", version = "^0.0.5", target = "lune" }

[indices]
default = "https://github.com/pesde-pkg/index"
